---
apiVersion: v1
kind: Secret
metadata:
  name: certbot-configuration
  labels:
    app.kubernetes.io/instance: serles
    app.kubernetes.io/name: serles
    app.kubernetes.io/version: 1.2.0
data:
  cloudflare.ini: >-
    ZG5zX2Nsb3VkZmxhcmVfYXBpX3Rva2VuID0gMDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nw==
  cli.ini: >-
    cHJlZmVycmVkLWNoYWxsZW5nZXM9ZG5zCmRucy1jbG91ZGZsYXJlCmRucy1jbG91ZGZsYXJlLWNyZWRlbnRpYWxzPS9ldGMvc2VybGVzL2Nsb3VkZmxhcmUuaW5pCgphZ3JlZS10b3MgPSB0cnVlCmVtYWlsID0gcGtpQGV4YW1wbGUuY29tCgprZXktdHlwZSA9IGVjZHNhCmVsbGlwdGljLWN1cnZlID0gc2VjcDM4NHIxCgpzZXJ2ZXIgPSBodHRwczovL2FjbWUuemVyb3NzbC5jb20vdjIvRFY5MAplYWIta2lkID0gc29tZXN0cmluZ29mc3R1ZmZ3aXRob3V0cXVvdGVzCmVhYi1obWFjID0geWFkZGF5YWRkYWhleGhleG5vdHF1b3RlZAoKIyBjZXJ0Ym90IGF0dGVtcHRzIHRvIHdyaXRlIHRvIHRoZXNlIHBhdGhzOyBvdmVyd3JpdGUgaWYgbm90IHJ1bm5pbmcgYXMgcm9vdDoKY29uZmlnLWRpcj0vZXRjL3Nlcmxlcy9sZXRzZW5jcnlwdAp3b3JrLWRpcj0vZXRjL3Nlcmxlcy9saWIvbGV0c2VuY3J5cHQKbG9ncy1kaXI9L2V0Yy9zZXJsZXMvbG9nL2xldHNlbmNyeXB0
